// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuikybhyjxkiwufxjygj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aWt5Ymh5anhraXd1ZnhqeWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzkwNzYsImV4cCI6MjA1MTE1NTA3Nn0.RU1jg2ny71G4p55vJ5BHxgaeTD34fRK10PWH9BJm_uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);